version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: etanol
      POSTGRES_DATABASE: etanol_development
      POSTGRES_PASSWORD: password