version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build:
    machine: true
    resource_class: medium
    steps:
      - checkout
      - eb/setup
#      - run:
#          name: Building Docker
#          command: docker build . -t $IMAGE_NAME --no-cache --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
#
#      - run:
#          name: Publish Docker Image to Docker Hub
#          command: |
#            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#            docker push $IMAGE_NAME:latest

#      - run:
#          name: Deploying to Elastic Bean Stalk
#          command: |
#            mkdir build
#            cp ./Dockerrun.aws.json ./build

        - run:
            name: Deploying to Elastic Bean Stalk
            command: |
              eb deploy

#          environment-name: etanol-prod
#          label: version-<<pipeline.number>>
#          app-dir: ./build
#          platform-version: docker
workflows:
  production:
    jobs:
      - build
          filters:
            branches:
              only: main
