version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build:
    machine: true
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
#      - run:
#          name: Building Docker
#          command: docker build . -t $IMAGE_NAME --no-cache --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
#
#      - run:
#          name: Publish Docker Image to Docker Hub
#          command: |
#            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#            docker push $IMAGE_NAME:latest

      - run:
          name: Updating Dockerrun.aws.json
          command: |
            mkdir build
            cp ./Dockerrun.aws.json ./build

      - run:
          name: Getting last commit message
          command: git log --pretty=format:%s -n 1 $CIRCLE_SHA1 >> commit.msg

      - persist_to_workspace:
          root: ~/repo
          paths:
            - Dockerrun.aws.json
            - commit.msg

  deploy:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - eb/setup
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploying to Elastic Bean Stalk
          command: |
            export GIT_COMMIT_DESC="$(cat ~/repo/commit.msg)"
            rm -f ~/repo/commit.msg
            sed -i='' "s|<IMAGE_NAME>|$IMAGE_NAME|" Dockerrun.aws.json
            sed -i='' "s|<TAG>|<<pipeline.number>>|" Dockerrun.aws.json
            eb init etanol -r $AWS_DEFAULT_REGION -p docker
            eb deploy etanol-prod --label version-<<pipeline.number>> --message $GIT_COMMIT_DESC
workflows:
  production:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build
